import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const files=['00-core.js','01-combat.js','02-update.js','03-render.js','04-ui-input.js','03-keyart-v026.js','03-living-color-v027.js','03-bosses-v028.js'];
const css=readFileSync('src/style.css','utf8').trim(),version=JSON.parse(readFileSync('package.json','utf8')).version;
let source=files.map(f=>{let s=readFileSync('src/'+f,'utf8');if(f=='00-core.js'){let a=s.indexOf('function shiftWalls('),b=s.indexOf('\nfunction drop(',a);if(a<0||b<0)throw Error('legacy shift seam missing');s=s.slice(0,a)+s.slice(b+1);a=s.indexOf('function spawnWave(');b=s.indexOf('\nfunction finale(',a);if(a<0||b<0)throw Error('legacy spawn seam missing');s=s.slice(0,a)+s.slice(b+1);s=s.replace('bp=1;bt=0;shiftWalls();','bp=1;bt=0;')}if(f=='01-combat.js')s=s.replace('for(let e of E){if(kickHit.includes(e))continue;','for(let e of E){if(e.g||kickHit.includes(e))continue;');if(f=='02-update.js'){s=s.replace('shiftUpdate(dt*f);','');let a=s.indexOf('else if(e.type==6){'),b=s.indexOf('else if(e.type==2||e.type==4){',a);if(a<0||b<0)throw Error('type6 boss seam missing');s=s.slice(0,a)+'else if(e.type==6){bossAI(e,dt,z)}'+s.slice(b);a=s.indexOf('else if(e.type==3){');b=s.indexOf('\n  e.vx*=',a);if(a<0||b<0)throw Error('type3 boss seam missing');s=s.slice(0,a)+'else if(e.type==3){bossAI(e,dt,z)}'+s.slice(b);s=s.replace('for(let e of [...E])if(Math.hypot(b.x-e.x,b.y-e.y)<e.r+b.r){','for(let e of [...E])if(!e.g&&Math.hypot(b.x-e.x,b.y-e.y)<e.r+b.r){')}if(f=='03-render.js'){let a=s.indexOf('function body('),b=s.indexOf('\nfunction block(',a);if(a<0||b<0)throw Error('character renderer seam missing');s=s.slice(0,a)+s.slice(b+1);a=s.indexOf('function worldArt(');b=s.indexOf('\nfunction scene(',a);if(a<0||b<0)throw Error('world renderer seam missing');s=s.slice(0,a)+s.slice(b+1)}if(f=='04-ui-input.js'){for(let [a0,b0] of [['function splash(','\nfunction demo('],['function intro(','\nfunction train('],['function mascot(','\nfunction page(']]){let a=s.indexOf(a0),b=s.indexOf(b0,a);if(a<0||b<0)throw Error('ui renderer seam missing');s=s.slice(0,a)+s.slice(b+1)}}if(f=='03-keyart-v026.js'){let a=s.indexOf('function intro('),b=s.indexOf('\nfunction mascot(',a);if(a<0||b<0)throw Error('v0.26 intro seam missing');s=s.slice(0,a)+s.slice(b+1);a=s.indexOf('function bossArt(');b=s.indexOf('\nfunction splash(',a);if(a<0||b<0)throw Error('v0.26 boss-art seam missing');s=s.slice(0,a)+s.slice(b+1)}return s}).join('\n');
for(let [a,b] of [['BOSS RUSH','ENCORE'],['BREAK THE HUSK ARCHITECT','KERNEL COLONEL'],['DEFEAT THE COBTOPUS','COBNOCOPIA'],['BEAT THE MAIZE MONARCH','HIDEAWAY HUSK'],['THE MAIZE MONARCH','HIDEAWAY HUSK'],['THE HUSK ARCHITECT','THE KERNEL COLONEL'],['THE COBTOPUS','THE COBNOCOPIA'],['CORN SWARM ','SWARM '],['DOUBLE? CHARGE!','DOUBLE!'],['SPARK ♥×','♥×'],['GOLD COB','2X COB'],['A UNICORN LAY IN TWO PIECES.','A UNICORN LAY BROKEN.'],['THE LAST RAINBOW FOUND THE WOUND.','THE LAST RAINBOW FOUND YOU.'],['PULL HEART AWAY UNTIL RAINBOW GLOWS.','PULL AWAY • RAINBOW GLOWS.'],['SPACE • RELEASE TENSION TO SNAP.','SPACE • RELEASE TO SNAP.'],['SCAR = MOVE + WEAPON + SECOND LIFE.','SCAR = MOVE + WEAPON + LIFE.']])source=source.replaceAll(a,b);
function mini(s){s=s.replace(/\/\*[\s\S]*?\*\//g,'').replace(/'use strict';/g,'');let o='',q='',e=0;for(let i=0;i<s.length;i++){let c=s[i];if(q){o+=c;if(e)e=0;else if(c=='\\')e=1;else if(c==q)q='';continue}if(c=="'"||c=='"'||c=='`'){q=c;o+=c;continue}if(/\s/.test(c)){let j=i+1;while(j<s.length&&/\s/.test(s[j]))j++;let a=o[o.length-1]||'',b=s[j]||'';if(/[\w$]/.test(a)&&/[\w$]/.test(b))o+=' ';i=j-1}else o+=c}return o}
let js=mini(source);
const gm={charge:'_0',ready:'_1',shake:'_2',state:'_3',sling:'_4',score:'_5',flash:'_6',shield:'_7',gold:'_8',nextWave:'_9',combo:'_a',slingA:'_b',queen:'_c',speed:'_d',runT:'_e',luckyT:'_f',kills:'_g',hitstop:'_h',pull:'_i',shot:'_j',snapT:'_k',comboT:'_l',voidX:'_m',voidY:'_n',msgT:'_o',kickHit:'_p',stageT:'_q',prime:'_r',curve:'_s',dead:'_t',tele:'_u',deathFX:'_z',kickCollisions:'_A',safeSpawn:'_B',rayW:'_C',hlen:'_D',beat:'_E',snap:'_F',over:'_G',team:'_I',bind:'_J',winT:'_K',reach:'_L',away:'_M',wantPull:'_N',targetLen:'_O',damp:'_P',boss:'_Q',armored:'_R',bonus:'_S',fire:'_T',burst:'_U',lucky:'_V',puff:'_W',chime:'_X',duo:'_Y',save:'_Z',wake:'$a',kp:'$b',killE:'$c',enemy:'$d',edge:'$e',wall:'$f',drop:'$g',bar:'$h',txt:'$i',body:'$j',uni:'$k',cob:'$l',block:'$m',scene:'$n',splash:'$o',mascot:'$p',title:'$q',page:'$r',keyname:'$t',controls:'$u',settings:'$v',panel:'$w',victory:'$x',draw:'$y',loop:'$z',reset:'$A',upd:'$B',startKick:'$C',hurt:'$D',music:'$E',snd:'S',say:'N',spawnWave:'$H',hitW:'$I',pop:'$J',wave:'L',hearts:'J',kick:'Z',kickA:'$N',inv:'Y',aim:'O',puT:'$Q',finale:'$0',wounds:'$1',grade:'$2',bp:'F',bt:'I'};
function golf(s){let o='',q='',e=0;for(let i=0;i<s.length;){let c=s[i];if(q){o+=c;i++;if(e)e=0;else if(c=='\\')e=1;else if(c==q)q='';continue}if(c=="'"||c=='"'||c=='`'){q=c;o+=c;i++;continue}if(/[A-Za-z_$]/.test(c)){let j=i+1;while(j<s.length&&/[\w$]/.test(s[j]))j++;let w=s.slice(i,j),m=gm[w],member=o[o.length-1]=='.';o+=m&&(!member||/^(state|curve|dead|tele|team)$/.test(w))?m:w;i=j}else{o+=c;i++}}return o}js=golf(js).replace('T=Math.PI*2','M=Math,T=M.PI*2').replace(/Math\./g,'M.');
const compShell='<meta charset=utf-8><style>'+css+'</style><canvas id=c width=960 height=640></canvas>';
const localShell='<meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><style>'+css+'</style><canvas id=c width=960 height=640></canvas>';
const html='<!doctype html>'+compShell+'<script>'+"'use strict';"+js+'</script>';
const fail="<script>onerror=(m)=>{let c=document.querySelector('#c'),x=c&&c.getContext('2d');if(x){x.fillStyle='#111';x.fillRect(0,0,c.width,c.height);x.fillStyle='#ff6b8a';x.font='20px monospace';x.fillText('Stretchicorn failed to start',40,70);x.fillStyle='#fff';x.font='14px monospace';let t=String(m);for(let i=0;i<t.length;i+=90)x.fillText(t.slice(i,i+90),40,110+i/90*22)}};</script>";
const local='<!doctype html><title>Stretchicorn v'+version+' local playtest</title>'+localShell+fail+'<script>'+source.replace(/<\/script/gi,'<\\/script')+'</script>';
mkdirSync('dist',{recursive:true});writeFileSync('dist/index.html',html);writeFileSync('dist/stretchicorn-local.html',local);console.log('dist/index.html',Buffer.byteLength(html),'bytes');console.log('dist/stretchicorn-local.html',Buffer.byteLength(local),'bytes (standalone file:// playtest)');