import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
const files=['00-core.js','01-combat.js','02-update.js','03-render.js','04-ui-input.js'];
const css=readFileSync('src/style.css','utf8').trim();
function mini(s){s=s.replace(/\/\*[\s\S]*?\*\//g,'').replace(/'use strict';/g,'');let o='',q='',e=0;for(let i=0;i<s.length;i++){let c=s[i];if(q){o+=c;if(e)e=0;else if(c=='\\')e=1;else if(c==q)q='';continue}if(c=="'"||c=='"'||c=='`'){q=c;o+=c;continue}if(/\s/.test(c)){let j=i+1;while(j<s.length&&/\s/.test(s[j]))j++;let a=o[o.length-1]||'',b=s[j]||'';if(/[\w$]/.test(a)&&/[\w$]/.test(b))o+=' ';i=j-1}else o+=c}return o}
let js=mini(files.map(f=>readFileSync('src/'+f,'utf8')).join('\n'));
// Safe size pass: rename only vetted internal identifiers, never text inside strings.
const gm={charge:'_0',ready:'_1',shake:'_2',state:'_3',sling:'_4',score:'_5',flash:'_6',shield:'_7',gold:'_8',nextWave:'_9',combo:'_a',slingA:'_b',queen:'_c',speed:'_d',runT:'_e',luckyT:'_f',kills:'_g',hitstop:'_h',pull:'_i',shot:'_j',snapT:'_k',comboT:'_l',voidX:'_m',voidY:'_n',msgT:'_o',kickHit:'_p',stageT:'_q',prime:'_r',curve:'_s',dead:'_t',tele:'_u',shiftWalls:'_v',eject:'_w',slamBlocks:'_x',shiftUpdate:'_y',deathFX:'_z',kickCollisions:'_A',safeSpawn:'_B',rayW:'_C',hlen:'_D',beat:'_E',snap:'_F',over:'_G',best:'_H',team:'_I',bind:'_J',winT:'_K',reach:'_L',away:'_M',wantPull:'_N',targetLen:'_O',damp:'_P',boss:'_Q',armored:'_R',bonus:'_S',fire:'_T',burst:'_U',lucky:'_V',puff:'_W',chime:'_X',duo:'_Y',save:'_Z',wake:'$a',kp:'$b',killE:'$c',enemy:'$d',edge:'$e',wall:'$f',drop:'$g',bar:'$h',txt:'$i',body:'$j',uni:'$k',cob:'$l',block:'$m',scene:'$n',splash:'$o',mascot:'$p',title:'$q',page:'$r',rules:'$s',keyname:'$t',controls:'$u',settings:'$v',panel:'$w',victory:'$x',draw:'$y',loop:'$z',reset:'$A',upd:'$B',startKick:'$C',hurt:'$D',music:'$E',snd:'S',say:'N',spawnWave:'$H',hitW:'$I',pop:'$J',wave:'L',hearts:'J',kick:'Z',kickA:'$N',inv:'Y',aim:'O',puT:'$Q',finale:'$0',bp:'F',bt:'I'};
function golf(s){let o='',q='',e=0;for(let i=0;i<s.length;){let c=s[i];if(q){o+=c;i++;if(e)e=0;else if(c=='\\')e=1;else if(c==q)q='';continue}if(c=="'"||c=='"'||c=='`'){q=c;o+=c;i++;continue}if(/[A-Za-z_$]/.test(c)){let j=i+1;while(j<s.length&&/[\w$]/.test(s[j]))j++;let w=s.slice(i,j),m=gm[w],member=o[o.length-1]=='.';o+=m&&(!member||/^(state|curve|dead|tele|team)$/.test(w))?m:w;i=j}else{o+=c;i++}}return o}js=golf(js).replace('T=Math.PI*2','M=Math,T=M.PI*2').replace(/Math\./g,'M.');
const html='<!doctype html><meta charset=utf-8><style>'+css+'</style><canvas id=c width=960 height=640></canvas><script>'+"'use strict';"+js+'</script>';
mkdirSync('dist',{recursive:true});writeFileSync('dist/index.html',html);console.log('dist/index.html',Buffer.byteLength(html),'bytes');