import {resolve} from'node:path';
import {pathToFileURL} from'node:url';
let playwright;
try{playwright=await import('playwright')}catch{console.error('Playwright is required. Install playwright@1.55.0');process.exit(2)}
const engine=process.env.BROWSER||process.argv[2]||'chromium',artifact=process.env.BROWSER_HTML||'dist/stretchicorn-local.html',launcher=playwright[engine];
if(!launcher||typeof launcher.launch!='function')throw Error(`Unsupported browser engine: ${engine}`);
const errors=[],consoleErrors=[],external=[];let browser;
try{
 browser=await launcher.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1280,height:800}});await context.addInitScript(()=>{const p=CanvasRenderingContext2D.prototype,f=p.fillText;p.fillText=function(s,...a){s=String(s);if(s==='PAUSED')window.__pauseSeen=1;if(s==='CONTROLS')window.__controlsSeen=1;if(s==='FIELD GUIDE')window.__guideSeen=1;if(s==='STRETCHICORN')window.__titleSeen=1;if(/^MOUSE (ON|OFF)$/.test(s))window.__pointerLabel=s;return f.call(this,s,...a)}});const page=await context.newPage();
 await page.route('**/*',async route=>{let u=new URL(route.request().url());if(u.protocol==='file:')return route.continue();external.push(u.href);return route.abort('blockedbyclient')});
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});
 await page.goto(pathToFileURL(resolve(artifact)).href,{waitUntil:'load',timeout:15000});
 const canvas=page.locator('#c');await canvas.waitFor({state:'visible',timeout:5000});await page.waitForTimeout(120);const box=await canvas.evaluate(n=>({w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height})),pos=(x,y)=>({x:box.w*x/960,y:box.h*y/640}),snap=()=>canvas.evaluate(n=>n.toDataURL()),label=()=>page.evaluate(()=>window.__pointerLabel||''),seen=k=>page.evaluate(k=>!!window[k],k),clear=(...ks)=>page.evaluate(ks=>ks.forEach(k=>window[k]=0),ks);
 await clear('__controlsSeen','__pointerLabel');await page.keyboard.press('c');await page.waitForTimeout(70);if(!await seen('__controlsSeen')||await label()!=='MOUSE ON')throw Error('local Controls did not render pointer ON');await page.keyboard.press('Enter');await page.waitForTimeout(70);if(await label()!=='MOUSE OFF')throw Error('local keyboard toggle did not render pointer OFF');await canvas.click({position:pos(480,440)});await page.waitForTimeout(70);
 await clear('__controlsSeen','__pointerLabel');await canvas.click({position:pos(550,535)});await page.waitForTimeout(70);if(!await seen('__controlsSeen')||await label()!=='MOUSE OFF')throw Error('local Controls click failed while pointer gameplay OFF');await canvas.click({position:pos(480,265)});await page.waitForTimeout(70);if(await label()!=='MOUSE ON')throw Error('local centered pointer toggle did not render ON');await canvas.click({position:pos(480,440)});await page.waitForTimeout(70);
 await clear('__guideSeen','__titleSeen');await canvas.click({position:pos(410,535)});await page.waitForTimeout(70);if(!await seen('__guideSeen'))throw Error('local Field Guide box did not open');await clear('__titleSeen');await canvas.click({position:pos(820,80)});await page.waitForTimeout(70);if(await seen('__titleSeen'))throw Error('local empty Guide click unexpectedly returned to title');await canvas.click({position:pos(480,545)});await page.waitForTimeout(70);if(!await seen('__titleSeen'))throw Error('local Guide BACK did not return to title');
 const title=await snap();await page.keyboard.press('t');await page.keyboard.press('Space');await page.waitForTimeout(180);const play=await snap();if(title===play)throw Error('local T intercepted title flow; Space did not reach gameplay');await clear('__pauseSeen');await page.keyboard.press('p');await page.waitForTimeout(120);if(!await seen('__pauseSeen'))throw Error('local T intercepted direct gameplay flow; PAUSED was never rendered');
 await clear('__guideSeen');await canvas.click({position:pos(410,295)});await page.waitForTimeout(70);if(!await seen('__guideSeen'))throw Error('local pause GUIDE did not open Guide');await clear('__pauseSeen');await canvas.click({position:pos(480,545)});await page.waitForTimeout(70);if(!await seen('__pauseSeen'))throw Error('local Guide BACK did not restore pause');await clear('__controlsSeen');await canvas.click({position:pos(550,295)});await page.waitForTimeout(70);if(!await seen('__controlsSeen'))throw Error('local pause CONTROLS did not open');await clear('__pauseSeen');await canvas.click({position:pos(480,440)});await page.waitForTimeout(70);if(!await seen('__pauseSeen'))throw Error('local Controls BACK did not restore pause');await canvas.click({position:pos(270,295)});await page.waitForTimeout(60);
 if(errors.length)throw Error(`page errors: ${errors.join(' | ')}`);if(consoleErrors.length)throw Error(`console errors: ${consoleErrors.join(' | ')}`);if(external.length)throw Error(`network requests attempted: ${[...new Set(external)].join(', ')}`);
 console.log(`PASS: ${engine} opened ${artifact} via file://, exercised centered Controls + boxed Guide/Back/pause clicks, kept empty Guide space inert, and reached gameplay`);await context.close();
}finally{if(browser)await browser.close()}
