import {readFileSync} from 'node:fs';import vm from'node:vm';
const h=readFileSync('dist/index.html','utf8'),m=h.match(/<script>([\s\S]*?)<\/script>/);if(!m)throw Error('inline script missing');if(/\bX\.[_$]/.test(m[1]))throw Error('unsafe Canvas API rename in build');let tones=0,wakes=0,raf;const p=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});function AC(){this.currentTime=0;this.destination={};this.resume=()=>{wakes++};this.createOscillator=()=>({type:'',frequency:p(),connect(){},start(){tones++},stop(){}});this.createGain=()=>({gain:p(),connect(){}})}
const x=new Proxy({}, {get:(o,k)=>o[k]||(o[k]=()=>{}),set:(o,k,v)=>(o[k]=v,true)}),c={getContext:()=>x,width:960,height:640},s={console,Math,Date,setTimeout:()=>{},clearTimeout:()=>{},requestAnimationFrame:f=>raf=f,document:{querySelector:()=>c},localStorage:{},AudioContext:AC,window:null};s.window=s;s.globalThis=s;vm.createContext(s);vm.runInContext(m[1],s);let now=0;const R=q=>vm.runInContext(q,s),frame=(n=1,ms=16.67)=>{for(let i=0;i<n;i++){let f=raf;if(!f)throw Error('RAF stopped');raf=null;f(now+=ms)}};R(`Object.defineProperties(globalThis,{charge:{get(){return _0},set(v){_0=v}},ready:{get(){return _1},set(v){_1=v}},fire:{get(){return _T},set(v){_T=v}},sling:{get(){return _4},set(v){_4=v}}})`);frame(3);
s.onkeydown({key:'Enter',repeat:false,preventDefault(){}});frame(5);if(R('mode')!==1||!wakes)throw Error('start/audio unlock');
// At 120 Hz one render frame occurs before each 60 Hz update. A Space tap must survive it.
R(`charge=1;ready=.5;kick=fire=acc=0;last=${now}`);s.onkeydown({key:' ',repeat:false,preventDefault(){}});frame(1,8.34);if(R('kick')!==0||R('fire')!==1)throw Error('120hz input lost');frame(1,8.34);if(R('kick')<=0||R('fire')!==0)throw Error('120hz input not consumed');
R('mode=0');s.onkeydown({key:'c',preventDefault(){}});s.onkeydown({key:'Enter',preventDefault(){}});s.onkeydown({key:'i',preventDefault(){}});if(R('BK[0]')!=='i')throw Error('rebind');s.onkeydown({key:'d',preventDefault(){}});s.onkeydown({key:'m',preventDefault(){}});s.onkeydown({key:'s',preventDefault(){}});s.onkeydown({key:'ArrowLeft',preventDefault(){}});if(R('V[1]')!=3)throw Error('settings');s.onkeydown({key:'m',preventDefault(){}});
let q=tones;R('V[1]=4;ms=32;mt=0');for(let i=0;i<32;i++)R('mt=0;music(1)');if(tones-q<20)throw Error('pop music absent');R('kick=sling=0;mode=1;wave=9;spawnWave()');if(R('bp')!==1||R('R.filter(o=>o.d).length')!==2)throw Error('huskshift warning absent');R('(()=>{let o=R.find(o=>o.d);A.x=o.x+o.w/2;A.y=o.y+o.h/2;hearts=13;inv=0;bt=1.99})()');R('upd(1/60)');if(R('bp')!==2||R('hearts')!==12)throw Error('huskshift impact absent');R('wave=13;spawnWave();bp=2;bt=2.34;upd(1/60)');if(R('bp')!==0)throw Error('cobtopus clear window absent');
R('reset()');for(let w=1;w<=13;w++){R(`wave=${w};spawnWave()`);if(R('!!hitW(A.x,A.y,24)||!!hitW(P.x,P.y,21)'))throw Error('unsafe stage '+w);R('for(let k in K)delete K[k];K.d=1;K.ArrowUp=1');for(let i=0;i<90;i++){if(i==25)R('startKick()');R('upd(1/60)')}if(!R('Number.isFinite(P.x+P.y+A.x+A.y)'))throw Error('nonfinite '+w)}
console.log('PASS: exact dist loads; 120Hz attack retention, HUSKSHIFT/Cobtopus, audio/mixer/rebind, all 13 stages stable');
