import assert from'node:assert/strict';import{readFileSync}from'node:fs';import vm from'node:vm';
const h=readFileSync('dist/stretchicorn-local.html','utf8'),code=[...h.matchAll(/<script>([\s\S]*?)<\/script>/g)].at(-1)[1],noop=()=>{},g={addColorStop:noop},X=new Proxy({createLinearGradient:()=>g,createRadialGradient:()=>g},{get:(o,k)=>o[k]||(o[k]=noop),set:(o,k,v)=>(o[k]=v,true)}),C={width:960,height:640,clientWidth:960,clientHeight:640,style:{},getContext:()=>X},storage={SK:'x|x|x|x|x|x|x|x|x',SV:'0,0'},M=Object.create(Math);let seed=13;M.random=()=>((seed=seed*1664525+1013904223>>>0)/4294967296);const s={console,Math:M,Date,localStorage:storage,setTimeout:noop,clearTimeout:noop,requestAnimationFrame:noop,document:{querySelector:()=>C,createElement:()=>C}};s.window=s;vm.createContext(s);vm.runInContext(code,s);const R=q=>vm.runInContext(q,s),key=k=>({repeat:false,key:k,preventDefault:noop}),mouse=(x=600,y=100)=>({button:0,offsetX:x,offsetY:y,preventDefault:noop});
assert.equal(R('SN.join(\"|\")'),"MORNING STRETCH|KERNEL PANIC|COB MOB|BALE OUT!|HIDEAWAY HUSK|GOLD RUSH|CRUNCH TIME|HAYWIRE|KERNEL COLONEL|POP QUIZ|HAYMAKER|LAST STRAW|CAP'N COBTOPUS",'final 13-trial naming contract');assert.equal(R('V[0]'),4,'retired legacy music mute must not strand current users without audio controls');assert.equal(R('V[1]'),4,'retired legacy SFX mute must not strand current users without audio controls');assert.equal(R('V[2]'),1,'legacy two-slot settings must migrate pointer gameplay ON');assert.equal(R('BK[0]'),'w','retired custom keybinds must not override the supported default controls');s.onkeydown(key('c'));assert.equal(R('mode'),6);s.onkeydown(key('Enter'));assert.equal(R('V[2]'),0);assert.match(String(storage.SV),/,0$/,'pointer OFF must persist');R('D=1;reset();aim=0;A.x=A.y=300;fire=0;mouseAimLive39=0');C.onmousemove(mouse());R('upd(1/60)');assert.equal(R('aim'),0,'disabled pointer motion changed horn aim');C.onmousedown(mouse());assert.equal(R('fire'),0,'disabled gameplay click triggered Snap');R('K.ArrowUp=1;upd(1/60);K.ArrowUp=0');assert.notEqual(R('aim'),0,'Arrow aim stopped when pointer gameplay was disabled');R('fire=0');s.onkeydown(key(' '));assert.equal(R('fire'),1,'Space Snap stopped when pointer gameplay was disabled');R('mode=2');s.onkeydown(key('c'));assert.equal(R('mode'),6);s.onkeydown(key('m'));assert.equal(R('mode'),2,'Controls opened from pause must return to pause');R('mode=0');C.onmousedown(mouse(550,535));assert.equal(R('mode'),6,'Controls title hit target failed while pointer gameplay was OFF');C.onmousedown(mouse());assert.equal(R('V[2]'),0,'empty Controls space must not toggle pointer gameplay');C.onmousedown(mouse(480,265));assert.equal(R('V[2]'),1,'centered Controls mouse action could not re-enable pointer gameplay');assert.equal(R('mouseAimLive39'),0,'re-enable must not resurrect a stale pointer target');C.onmousedown(mouse(480,440));assert.equal(R('mode'),0,'centered Controls Back must restore title');R('mode=1;aim=0;fire=0;A.x=A.y=300');C.onmousemove(mouse());R('upd(1/60)');assert.notEqual(R('aim'),0,'re-enabled pointer motion did not regain aim authority');C.onmousedown(mouse());assert.equal(R('fire'),1,'re-enabled gameplay click did not regain Snap authority');
R('D=2.4;hearts=5;shield=0;score=0;charge=ready=0;lucky()');assert.equal(R('hearts'),6,'Impossible Lucky 13 must restore one heart');assert.equal(R('shield'),1,'Impossible Lucky 13 must restore shield sustain');assert.equal(R('score'),130,'Lucky 13 Style bonus must remain intact');
R('D=2.4;mode=1;score=30000;save()');assert.equal(R('score'),90000,'Impossible run-end Style premium must be 3x');assert.equal(+storage['SB2.4'],90000,'Impossible Best must persist the premium score');
R('D=1.6;mode=1;score=120000;save()');assert.equal(R('score'),120000,'Hard score scale must remain unchanged');
R('D=2.4;mode=6;score=30000;save()');assert.equal(R('score'),30000,'Controls save must never trigger the Impossible score premium');
R('D=1.6;reset(9);score=200;kills=12;combo=1;let m=enemy(2,120,180);m.in=0;killE(m)');assert.equal(R('score'),200,'Kernel Colonel summons must not create farmable Style');assert.equal(R('kills'),12,'boss summons must not advance Lucky 13 farming');assert.equal(R('combo'),1,'boss summons must not inflate combo before the boss clear');
R('D=1.6;reset(9);score=200;hearts=1e6;inv=1e6;A.x=A.y=300;B.length=0;B.push({x:340,y:300,vx:0,vy:0,team:2,r:5,l:5});V[0]=V[1]=0;upd(1/60)');assert.equal(R('score'),200,'repeatable boss grazes must be score-neutral');assert.equal(R('B[0].g'),1,'boss graze must still grant its tactical interaction');
R('D=1.6;reset(9);score=200;hearts=1e6;inv=1e6;A.x=A.y=300;aim=0;U.length=0;U.push({type:2,x:325,y:300,l:7});V[0]=V[1]=0;upd(1/60)');assert.equal(R('score'),200,'repeatable boss pickups must be score-neutral');assert.equal(R('speed>0'),true,'boss pickup must still grant its survival effect');
R('D=1.6;reset(2);hearts=1e6;inv=1e6;V[0]=V[1]=0;E.splice(1);U.length=0;puT=0;upd(1/60)');assert.equal(R('U.length'),0,'Hard must not spawn passive pickups while one regular enemy is intentionally preserved');R('edge(0);upd(1/60)');assert.equal(R('U.length'),1,'Hard pickup clock must resume under meaningful regular-wave pressure');
R('D=1.6;reset(2);hearts=1e6;inv=1e6;V[0]=V[1]=0;puT=1;upd(.16)');const hardPu=R('puT');R('D=2.4;reset(2);hearts=1e6;inv=1e6;V[0]=V[1]=0;puT=1;upd(.16)');assert.ok(Math.abs(R('puT')-hardPu)<1e-9,'Impossible pickup scarcity must cap at Hard cadence');R('D=2.4;reset(9);hearts=1e6;inv=1e6;V[0]=V[1]=0;E.splice(1);U.length=0;puT=0;upd(1/60)');assert.equal(R('U.length'),1,'Impossible bosses must retain sustain even when only the boss remains');
R('mode=1;wave=1;bp=2;R.length=E.length=0;wall(75,120,110,80,1);var z=enemy(0,70,110);z.in=0;hearts=inv=1e6;V[0]=V[1]=0;upd(1/60)');assert.equal(R('!!hitW(E[0].x,E[0].y,E[0].r)'),false,'enemy embedded against world bound must escape hardened hay');
R('mode=1;wave=1;bp=2;R.length=E.length=0;wall(90,270,110,80,1);wall(220,405,115,90,1);var z=enemy(6,192,351);z.in=0;hearts=inv=1e6;V[0]=V[1]=0;upd(1/60)');assert.equal(R('!!hitW(E[0].x,E[0].y,E[0].r)'),false,'large enemy must escape multi-block containment');
R('mode=1;wave=12;bp=2;R.length=0;wall(300,250,110,82,1);E.length=0;var h=enemy(5,330,290);h.in=-1;killE(h);hearts=inv=1e6;V[0]=V[1]=0;upd(1/60)');assert.equal(R('E.every(e=>!hitW(e.x,e.y,e.r))'),true,'husk split children must escape active hay');
for(const w of[9,12,13]){const ok=R(`D=2.4;reset(${w});hearts=inv=1e6;V[0]=V[1]=0;var ok=1;for(var i=0;i<1200;i++){upd(1/60);if(bp==2&&E.some(e=>e.in<=0&&hitW(e.x,e.y,e.r))){upd(1/60);if(bp==2&&E.some(e=>e.in<=0&&hitW(e.x,e.y,e.r))){ok=0;break}}}ok`);assert.equal(ok,1,`active hay persistently embedded a live enemy, trial=${w}`)}
const finite=()=>R('[A,P,...E,...B,...U].every(o=>Object.values(o).every(v=>typeof v!=="number"||Number.isFinite(v)))');for(const d of[.7,1,1.6,2.4])for(const w of[1,5,9,13]){R(`D=${d};reset(${w});hearts=1e6;inv=1e6;shield=1;V[0]=V[1]=0;B.length=U.length=0`);for(let i=0;i<900;i++)R('upd(1/60)');assert.equal(finite(),true,`non-finite simulation state at D=${d}, trial=${w}`);assert.ok(R('B.length')<1000,`projectile runaway at D=${d}, trial=${w}`);assert.ok(R('E.length')<80,`enemy runaway at D=${d}, trial=${w}`);assert.equal(R('mode'),1,`soak escaped gameplay at D=${d}, trial=${w}`)}
console.log('PASS: release audit covers centered Controls, anti-farm boss Style, Hard/Impossible pickup gating, restored Impossible Lucky sustain, and dynamic-block containment and deterministic boss/difficulty soak');
