import{readFileSync}from'node:fs';import vm from'node:vm';
const h=readFileSync('dist/index.html','utf8'),m=h.match(/<script>([\s\S]*?)<\/script>/),bs=readFileSync('src/03-bosses-v028.js','utf8'),bu=readFileSync('scripts/build.mjs','utf8');if(!m)throw Error('script missing');for(const q of['THE LIVING SCAR','FIRST FLIGHT','HIDEAWAY HUSK','THE KERNEL COLONEL','THE COBNOCOPIA','PARRY KERNELS'])if(!h.includes(q))throw Error('missing '+q);if(/\bX\.[_$]/.test(m[1]))throw Error('Canvas API golf');if(!bu.includes('b.team=3')||!bu.includes('lateBlocks(dt);')||!bu.includes("if(!e.b){'+face+'}"))throw Error('build contracts');if(!bs.includes('fillRect(-28,-r*.72,64,16)')||!bs.includes('X.moveTo(x-18,-19)')||!bs.includes('X.lineTo(x-4,-23)')||!bs.includes('quadraticCurveTo(x-8,25,x,14)'))throw Error('Colonel face/cap contract');
let wakes=0;const p=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});function AC(){this.currentTime=0;this.destination={};this.resume=()=>wakes++;this.createOscillator=()=>({frequency:p(),connect(){},start(){},stop(){}});this.createGain=()=>({gain:p(),connect(){}});this.createBiquadFilter=()=>({frequency:p(),Q:p(),connect(){},type:''})}const gg={addColorStop(){}},x=new Proxy({createLinearGradient:()=>gg},{get:(o,k)=>o[k]||(o[k]=()=>{}),set:(o,k,v)=>(o[k]=v,true)}),c={getContext:()=>x,width:960,height:640},s={console,Math,Date,setTimeout:()=>{},clearTimeout:()=>{},requestAnimationFrame:()=>{},document:{querySelector:()=>c,createElement:()=>c},localStorage:{SV:'0,0'},AudioContext:AC,window:null};s.window=s;s.globalThis=s;vm.createContext(s);vm.runInContext(m[1],s);const R=q=>vm.runInContext(q,s),key=k=>s.onkeydown({key:k,repeat:false,preventDefault(){}});R('globalThis.reset=$A;globalThis.upd=$B;globalThis.spawnWave=$H;globalThis.hitW=$I;globalThis.killE=$c;globalThis.enemy=$d;globalThis.lucky=_V;globalThis.kickCollisions=_A');
for(const[k,d,n]of[['1',.7,3],['2',1,5],['3',1.6,8],['4',2.4,8]]){R('mode=0');key(k);s.onkeyup({key:k});if(Math.abs(R('D')-d)>1e-9||R('mode')!=1||R('E.length')!=n)throw Error('difficulty '+k)}R('mode=9');key(' ');if(R('mode')!=10||R('E.length'))throw Error('First Flight entry');key('Escape');if(R('mode')!=1||R('D')!=.7||R('E.length')!=3)throw Error('First Flight handoff');if(!wakes)throw Error('audio wake');
R('mode=1;D=1;E.length=B.length=0;A.x=300;A.y=300;P.x=350;P.y=300;O=0;_j=1;$N=0;Z=.1;_4=0;_F=1;_p=[];B.push({x:504,y:300,vx:0,vy:0,_I:2,r:10,l:2});kickCollisions()');if(R('B[0]._I')!=3)throw Error('large parry');R('B.length=0;B.push({x:504,y:300,vx:0,vy:0,_I:2,r:4,l:2});kickCollisions()');if(R('B[0]._I')!=2)throw Error('radius-aware parry');R('B.length=0;B.push({x:459,y:300,vx:0,vy:0,_I:1,r:8,l:2});kickCollisions()');if(R('B[0]._I')!=1)throw Error('piercing parried');
const shot=w=>{R(`mode=1;D=1;L=${w};E.length=B.length=0;A.x=700;A.y=300;(()=>{let e=enemy(2,300,300);e.cd=0;upd(.01)})()`);return R('[B[0].r,Math.hypot(B[0].vx,B[0].vy)]')},a=shot(6),b=shot(12);if(!(a[0]>b[0]&&a[1]<b[1]))throw Error('projectile progression '+a+'/'+b);R('mode=1;D=2.4;E.length=B.length=0;A.x=300;A.y=300;J=13;Y=99;B.push({x:300,y:300,vx:0,vy:0,_I:1,r:8,l:2});upd(1/60)');if(R('J')!=12)throw Error('piercing invulnerability');
R('R.length=0;F=I=0;L=8;lateBlocks(5)');if(R('R.length'))throw Error('early dynamic block');R('R.length=0;F=I=0;L=11;lateBlocks(.8)');if(R('R.length'))throw Error('wave11 cadence');R('R.length=0;F=I=0;L=9;lateBlocks(1.2)');if(R('R.filter(o=>o.d).length')!=1)throw Error('wave9 block');R('R.length=0;F=I=0;L=12;lateBlocks(.8)');if(R('R.filter(o=>o.d).length')!=2)throw Error('late block pair');
R('mode=1;D=1;L=5;spawnWave();A.x=100;A.y=500;E[0].in=0;E[0]._3=1;E[0]._u=.001;E[0].g=1;B.length=0;bossAI(E[0],.01,.01)');if(!R('E[0]._3==2&&!E[0].g&&B.length==7&&B.every(b=>b._I==1)'))throw Error('Hideaway cover/open');
R('mode=1;D=1;L=9;spawnWave();E[0].in=0;E[0].cd=99;for(let i=0;i<3;i++)killE(enemy(0,200+i*25,200))');if(R('E[0].p')!=3)throw Error('Colonel chain');R('bossAI(E[0],.01,.01)');if(R('E[0].g'))throw Error('Colonel exposure');R('E[0].s=.001;E[0].cd=99;bossAI(E[0],.01,.01)');if(!R('E[0].g&&E[0].p==0'))throw Error('Colonel guard restore');R('E[0].cd=0;bossAI(E[0],.01,.01)');if(R('E.length')!=5)throw Error('Colonel squad');
R('mode=1;D=1;L=13;spawnWave();_h=0;A.x=100;A.y=500;let e=E.find(e=>e.b==3);e.in=99;globalThis.hh=e.hp;B.length=0;B.push({x:e.x,y:e.y,vx:0,vy:0,_I:3,r:5,l:2});upd(.001)');if(!R('E.find(e=>e.b==3).g&&E.find(e=>e.b==3).p==1')||R('E.find(e=>e.b==3).hp')!=R('hh'))throw Error('Cob first parry');R('(()=>{let e=E.find(e=>e.b==3);B.push({x:e.x,y:e.y,vx:0,vy:0,_I:3,r:5,l:2});upd(.001)})()');if(!R('(()=>{let e=E.find(e=>e.b==3);return !e.g&&e._3==1&&e.p==0})()'))throw Error('Cob parry open');R('L=13;spawnWave();A.x=100;A.y=500;(()=>{let e=E.find(e=>e.b==3),q=E.find(e=>e.h);e.hp=e.max-5;e.in=0;globalThis.hh=e.hp;q.x=e.x;q.y=e.y;bossAI(e,.001,.001)})()');if(R('E.find(e=>e.b==3).hp')!=R('hh')+3||R('E.filter(e=>e.h).length')!=1)throw Error('Cob heal');R('L=13;spawnWave();for(let i=E.length;i--;)if(E[i].h)E.splice(i,1);(()=>{let e=E.find(e=>e.b==3);e.in=0;e.hp=e.max*.19;bossAI(e,.001,.001)})()');if(R('E.filter(e=>e.h).length')!=6)throw Error('Final Feast');
for(const d of[1.6,2.4]){R(`mode=1;D=${d};L=13;spawnWave();killE(E.find(e=>e.b==3))`);if(R('mode')!=1||R('E.filter(e=>e.b==4).length')!=2||R('_c')!=4||R('E.some(e=>e.h)'))throw Error('twins '+d);R('killE(E.find(e=>e.b==4))');if(R('mode')!=1||R('E.filter(e=>e.b==4).length')!=1||R('_c')!=3)throw Error('first twin '+d);R('killE(E.find(e=>e.b==4))');if(R('mode')!=5||R('_c')!=2)throw Error('second twin '+d)}
R('D=2.4;J=7;_7=0;_0=0;_1=0;_5=0;lucky()');if(R('J')!=7||R('_7')||R('_0')<.5||R('_5')!=130)throw Error('Impossible Lucky');for(let w=1;w<=13;w++){R(`mode=1;D=1;L=${w};spawnWave()`);if(R('!!hitW(A.x,A.y,24)||!!hitW(P.x,P.y,21)'))throw Error('unsafe '+w)}R('D=1;reset();mode=1;K.w=1;_T=1');s.onblur();if(R('mode')!=2||R('_T')||R('Object.keys(K).length'))throw Error('blur pause');
console.log('PASS: v0.29 parry progression, late blocks, authored boss state machines, healing and two-Cobtopus finale');
