import{readFileSync}from'node:fs';import vm from'node:vm';
const s=readFileSync('src/03-title-v037.js','utf8'),sky=readFileSync('src/03-sky-v030.js','utf8');let resets=0,woke=0,base=0,prevented=0,fills=0;
const X={fillRect(){fills++},strokeRect(){},beginPath(){},moveTo(){},lineTo(){},stroke(){},save(){},restore(){},translate(){},scale(){}};
const C={getBoundingClientRect:()=>({left:0,top:0,width:960,height:640})};
const c={console,Math,X,C,W:960,H:640,mode:0,kick:0,K:{},BK:['w','s','a','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '],aim:0,A:{x:100,y:100},bp:0,bt:0,fire:0,wave:1,ready:0,RC:['','','','','',''],D:1,block(){},upd(){base++},draw(){},reset(){resets++;c.mode=1},ad:(a,b)=>Math.atan2(Math.sin(b-a),Math.cos(b-a)),cl:(v,a,b)=>v<a?a:v>b?b:v,wake(){woke++},ink(k,w){X.strokeStyle=k;X.lineWidth=w},txt(){},splash(){},page(){},demo(){},co31(){}};
vm.createContext(c);vm.runInContext(s,c);let ev=(x,y)=>({button:0,clientX:x,clientY:y,preventDefault(){prevented++}});
c.C.onmousedown(ev(520,470));if(Math.abs(c.D-1.6)>1e-9||resets!==1||c.mode!==1||woke!==1)throw Error('clicking HARD did not start matching difficulty');
c.mode=0;c.C.onmousedown(ev(480,535));if(c.mode!==7)throw Error('field guide did not open');c.C.onmousedown(ev(820,80));if(c.mode!==0)throw Error('field guide did not close');
c.mode=1;c.aim=0;c.C.onmousemove({clientX:100,clientY:0});c.upd(1/60);if(!(c.aim<0&&c.aim>=-.251)||base!=1)throw Error('mouse aim lost shared slew/base update');c.aim=0;c.K.ArrowUp=1;c.upd(1/60);if(c.aim)throw Error('mouse aim must yield to keyboard');c.K.ArrowUp=0;c.C.onmousedown(ev(100,100));if(c.fire!=1)throw Error('click did not route to Snap');c.C.onmouseleave();c.aim=0;c.upd(1/60);if(c.aim)throw Error('mouse aim stayed live after leave');
fills=0;c.block({x:20,y:20,w:110,h:80,d:0});if(fills<18)throw Error('bale layering missing');
for(const q of['CLICK/1-4','GOAL  13 TRIALS','SNAP AGAIN=DOUBLE','CYAN ◆ DODGE','HAY ▨ FORMS→WALL→GONE',"'#c89452'","'#e6bd79'","'#666b42'",'getBoundingClientRect','fire=1'])if(!s.includes(q))throw Error('missing v0.40 contract: '+q);if(sky.includes('x+18,y-15')||sky.includes('globalAlpha=.08+z*.16'))throw Error('stray background streaks returned');if(prevented<4)throw Error('pointer actions must suppress browser defaults');
console.log('PASS: stacked onboarding, mouse controls, cleaner dimensional hay and streak-free sky');
