import{readFileSync}from'node:fs';import vm from'node:vm';
const h=readFileSync('dist/index.html','utf8'),m=h.match(/<script>([\s\S]*?)<\/script>/);if(!m)throw Error('script missing');for(const q of['THE LIVING SCAR','FIRST FLIGHT','COBTOPUS PRIME','ROUND KERNELS','BODY TAKES DAMAGE','SHIELD CLOSED','PHASE II'])if(!h.includes(q))throw Error('missing '+q);
let wakes=0,ell=[];const p=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});function AC(){this.currentTime=0;this.destination={};this.resume=()=>wakes++;this.createOscillator=()=>({frequency:p(),connect(){},start(){},stop(){}});this.createGain=()=>({gain:p(),connect(){}});this.createBiquadFilter=()=>({frequency:p(),Q:p(),connect(){},type:'lowpass'})}
const gg={addColorStop(){}};const x=new Proxy({createLinearGradient:()=>gg,ellipse:(x,y,a,b)=>ell.push([a,b])},{get:(o,k)=>o[k]||(o[k]=()=>{}),set:(o,k,v)=>(o[k]=v,true)}),c={getContext:()=>x,width:960,height:640},s={console,Math,Date,setTimeout:()=>{},clearTimeout:()=>{},requestAnimationFrame:()=>{},document:{querySelector:()=>c,createElement:()=>c},localStorage:{SV:'0,0'},AudioContext:AC,window:null};s.window=s;s.globalThis=s;vm.createContext(s);vm.runInContext(m[1],s);const R=q=>vm.runInContext(q,s),key=k=>s.onkeydown({key:k,repeat:false,preventDefault(){}});
R(`Object.defineProperties(globalThis,{wave:{get(){return L},set(v){L=v}},hearts:{get(){return J},set(v){J=v}},queen:{get(){return _c},set(v){_c=v}},bp:{get(){return F},set(v){F=v}},bt:{get(){return I},set(v){I=v}}});globalThis.upd=$B;globalThis.spawnWave=$H;globalThis.killE=$c;globalThis.hitW=$I`);
for(const[k,d,n]of[['1',.7,3],['2',1,5],['3',1.6,8],['4',2.4,8]]){R('mode=0');key(k);s.onkeyup({key:k});if(Math.abs(R('D')-d)>1e-9||R('E.length')!==n)throw Error('difficulty '+k)}
R('mode=9;stageT=3');R('intro()');if(!R('stageT==3'))throw Error('intro state');R('mode=1;D=1;wave=5;spawnWave();E[0].in=0;E[0]._u=.001;upd(.01)');if(!R('E[0]._3==1&&E[0].g&&bp==1'))throw Error('Hideaway warning');R('E[0]._u=.001;upd(.01)');if(!R('E[0]._3==2&&!E[0].g&&bp==2&&B.length==7'))throw Error('Hideaway open');
R('mode=1;D=.7;wave=9;spawnWave();E[0].in=0;B.length=0;B.push({x:E[0].x,y:E[0].y,vx:0,vy:0,_I:1,r:7,l:2});upd(1/60)');if(!R('req31()==1&&E[0].p==1&&!E[0].g'))throw Error('Colonel return gate');
R('mode=1;D=.7;wave=13;spawnWave();E[0].in=0');if(!R("SN[12]=='COBTOPUS PRIME'&&final31==1&&E.length==1&&E[0].b==4&&E[0].g"))throw Error('Prime phase');R('E[0]._3=1;E[0]._u=.001;B.length=0;upd(.01)');if(!R('E[0]._3==2&&!E[0].g&&bp==2&&B.length==6'))throw Error('Prime open window');R('killE(E[0])');if(!R('final31==2&&need31==1&&E.filter(e=>e.b==3).length==2&&E.every(e=>e.g)'))throw Error('split phase');R('B.push({x:E[0].x,y:E[0].y,vx:0,vy:0,_I:1,r:7,l:2});upd(1/60)');if(!R('!E[0].g&&E[1].g'))throw Error('independent core gate');R('killE(E[0])');if(!R('mode==1&&E.filter(e=>e.b==3).length==1'))throw Error('first core ended fight');R('B.push({x:E[0].x,y:E[0].y,vx:0,vy:0,_I:1,r:7,l:2});upd(1/60);killE(E[0])');if(R('mode')!==5)throw Error('final core ending');
R('mode=1;D=2.4;wave=13;spawnWave();killE(E[0])');if(R('need31')!==4)throw Error('Impossible return count');
ell.length=0;R("oval(0,0,7,3.5,'#e9b83e')");if(!ell.length||ell.at(-1)[0]!==ell.at(-1)[1])throw Error('returnable kernel not round');
for(let w=1;w<=13;w++){R(`mode=1;D=1;wave=${w};spawnWave()`);if(R('!!hitW(A.x,A.y,24)||!!hitW(P.x,P.y,21)'))throw Error('unsafe '+w)}
console.log('PASS: v0.31 concise connected intro, explicit danger rules, round returnable kernels, authored Hideaway/Colonel gates, two-phase Cobtopus Prime, independent split-core counters, difficulty scaling, safe stages');
