import {readFileSync} from 'node:fs'; import vm from 'node:vm';
const h=readFileSync('dist/index.html','utf8'),m=h.match(/<script>([\s\S]*?)<\/script>/); if(!m)throw Error('script missing');
let tones=0,filters=0;const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});function AC(){this.currentTime=0;this.destination={};this.createOscillator=()=>({frequency:param(),connect(){},start(){tones++},stop(){}});this.createGain=()=>({gain:param(),connect(){}});this.createBiquadFilter=()=>(filters++,{frequency:param(),Q:param(),connect(){}})}
const x=new Proxy({}, {get:(o,k)=>o[k]||(o[k]=()=>{}),set:(o,k,v)=>(o[k]=v,true)}),c={getContext:()=>x,width:960,height:640};
const s={console,Math,Date,setTimeout:()=>{},clearTimeout:()=>{},requestAnimationFrame:()=>{},document:{querySelector:()=>c},localStorage:{},AudioContext:AC,window:null};s.window=s;s.globalThis=s;vm.createContext(s);vm.runInContext(m[1],s);const g=s.__SR;if(!g)throw Error('__SR missing');
// UI regression: Enter must start and enter rebind mode, and duplicate bindings swap instead of aliasing two actions.
vm.runInContext('mode=0',s);s.onkeydown({key:'Enter',preventDefault(){}});if(g.get().mode!==1)throw Error('Enter did not start game');vm.runInContext('mode=0',s);s.onkeydown({key:'c',preventDefault(){}});s.onkeydown({key:'Enter',preventDefault(){}});s.onkeydown({key:'i',preventDefault(){}});let binds=vm.runInContext('BK.slice()',s);if(binds[0]!=='i')throw Error('Enter rebind failed');s.onkeydown({key:'ArrowDown',preventDefault(){}});s.onkeydown({key:'Enter',preventDefault(){}});s.onkeydown({key:'i',preventDefault(){}});binds=vm.runInContext('BK.slice()',s);if(binds[1]!=='i'||binds[0]!=='s')throw Error('duplicate binding swap failed');s.onkeydown({key:'d',preventDefault(){}});
// Settings: music and game sounds are independent 0..100% controls.
vm.runInContext('mode=0',s);s.onkeydown({key:'s',preventDefault(){}});if(g.get().mode!==8)throw Error('settings page failed');s.onkeydown({key:'ArrowLeft',preventDefault(){}});if(g.get().mv!==3||g.get().sv!==4)throw Error('music volume failed');s.onkeydown({key:'ArrowDown',preventDefault(){}});s.onkeydown({key:'ArrowLeft',preventDefault(){}});if(g.get().sv!==3)throw Error('SFX volume failed');s.onkeydown({key:'m',preventDefault(){}});
// Mixer actually gates each audio class independently.
let n0=tones;vm.runInContext('V[0]=0;snd(440)',s);if(tones!==n0)throw Error('SFX off still scheduled sound');vm.runInContext('V[0]=4;V[1]=0;mt=0',s);n0=tones;for(let i=0;i<4;i++)g.upd(1/60);if(tones!==n0)throw Error('music off still scheduled music');vm.runInContext('V[1]=4',s);
g.reset();if(g.get().hearts!==13)throw Error('expected 13 hearts');for(let i=0;i<65;i++)g.upd(1/60);if(tones<5||!filters)throw Error('procedural bass engine did not schedule');g.clear();g.setKeys({ArrowUp:1});for(let i=0;i<4;i++)g.upd(1/60);if(Math.abs(g.get().aim)<.9)throw Error('head steering too sluggish');g.clear();
// Attack angle must be snapshotted: rotating during an active horn extension cannot bend its hit direction.
vm.runInContext('aim=0;charge=.1;ready=0',s);g.startKick();let ka=g.get().kickA;g.setKeys({ArrowUp:1});for(let i=0;i<5;i++)g.upd(1/60);if(Math.abs(g.get().aim-ka)>.02||Math.abs(g.get().kickA-ka)>.02)throw Error('attack direction changed while horn active');g.clear();
for(let w=1;w<=13;w++){g.wave(w);let q=g.get();if(q.rearBlocked||q.headBlocked)throw Error('unsafe spawn '+w);for(let f=0;f<360;f++){if(!(f%60)){g.clear();g.setKeys([{d:1},{s:1},{a:1},{w:1},{ArrowUp:1},{ArrowRight:1}][(w+f/60)%6])}if(!(f%103))g.startKick();g.upd(1/60);q=g.get();if(!Number.isFinite(q.head.x+q.head.y+q.rear.x+q.rear.y))throw Error('non-finite state')}}
console.log('PASS: settings, 13 lives, rebinds, 13 safe stages, spring/combat stable, set-style soundtrack + precise horn active');
