import{readFileSync}from'node:fs';import vm from'node:vm';
const h=readFileSync('dist/index.html','utf8'),m=h.match(/<script>([\s\S]*?)<\/script>/);if(!m)throw Error('script missing');for(const q of['COBTOPUS PRIME','HUSK SHIELD BLOCKS HITS','SHIELD OPEN','PHASE SHIFT','ROUND KERNELS','RETURN x','PHASE II'])if(!h.includes(q))throw Error('missing '+q);
let ell=[];const p=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});function AC(){this.currentTime=0;this.destination={};this.resume=()=>{};this.createOscillator=()=>({frequency:p(),connect(){},start(){},stop(){}});this.createGain=()=>({gain:p(),connect(){}});this.createBiquadFilter=()=>({frequency:p(),Q:p(),connect(){},type:'lowpass'})}
const gg={addColorStop(){}};const x=new Proxy({createLinearGradient:()=>gg,ellipse:(x,y,a,b)=>ell.push([a,b])},{get:(o,k)=>o[k]||(o[k]=()=>{}),set:(o,k,v)=>(o[k]=v,true)}),c={getContext:()=>x,width:960,height:640},s={console,Math,Date,setTimeout:()=>{},clearTimeout:()=>{},requestAnimationFrame:()=>{},document:{querySelector:()=>c,createElement:()=>c},localStorage:{SV:'0,0'},AudioContext:AC,window:null};s.window=s;s.globalThis=s;vm.createContext(s);vm.runInContext(m[1],s);const R=q=>vm.runInContext(q,s),key=k=>s.onkeydown({key:k,repeat:false,preventDefault(){}});
R(`Object.defineProperties(globalThis,{wave:{get(){return L},set(v){L=v}},hearts:{get(){return J},set(v){J=v}},queen:{get(){return _c},set(v){_c=v}},bp:{get(){return F},set(v){F=v}},bt:{get(){return I},set(v){I=v}},shot:{get(){return _j},set(v){_j=v}},kick:{get(){return Z},set(v){Z=v}},kickA:{get(){return $N},set(v){$N=v}},sling:{get(){return _4},set(v){_4=v}},snap:{get(){return _F},set(v){_F=v}},kickHit:{get(){return _p},set(v){_p=v}},hitstop:{get(){return _h},set(v){_h=v}}});globalThis.upd=$B;globalThis.spawnWave=$H;globalThis.killE=$c;globalThis.hitW=$I;globalThis.kickCollisions=_A`);
for(const[k,d,n]of[['1',.7,3],['2',1,5],['3',1.6,8],['4',2.4,8]]){R('mode=0');key(k);s.onkeyup({key:k});if(Math.abs(R('D')-d)>1e-9||R('E.length')!==n)throw Error('difficulty '+k)}
R('mode=1;D=1;wave=5;hitstop=0;spawnWave();E[0].in=0;globalThis.e=E[0];P.x=e.x-40;P.y=e.y;A.x=P.x-54;A.y=P.y;shot=.5;kickA=0;kick=.1;sling=.1;snap=2;kickHit=[];globalThis.hh=e.hp;kickCollisions()');if(R('e.hp')!==R('hh'))throw Error('Husk shield penetrated');if(R('R.length'))throw Error('Hideaway should begin as clean duel');R('hitstop=0;e._u=.001;upd(.01)');if(!R('e._3==1&&e.g'))throw Error('Husk opening tell');R('hitstop=0;e._u=.001;upd(.01)');if(!R('e._3==2&&!e.g'))throw Error('Husk firing window did not open');R('hitstop=0;B.length=0;upd(.01)');if(!R('B.length>=5'))throw Error('Husk did not fire while exposed');
R('B.length=0;globalThis.hr=e.hp;B.push({x:e.x,y:e.y,vx:0,vy:0,_I:1,r:7,l:2,p:999});upd(.001)');if(R('hr-e.hp')!==2)throw Error('close return damage');R('B.length=0;globalThis.hr=e.hp;B.push({x:e.x,y:e.y,vx:0,vy:0,_I:1,r:7,l:2,p:-999});upd(.001)');if(R('hr-e.hp')!==4)throw Error('long return damage');R('e.g=1;B.length=0;globalThis.hr=e.hp;B.push({x:e.x,y:e.y,vx:0,vy:0,_I:1,r:7,l:2,p:-999});upd(.001)');if(R('hr-e.hp')!==0)throw Error('return pierced closed Husk shield');R('e.g=0');
R('B.length=0;P.x=e.x-40;P.y=e.y;A.x=P.x-54;A.y=P.y;shot=.5;kickA=0;kick=.1;sling=.1;snap=2;for(let i=0;i<3;i++){kickHit=[];kick=.1;kickCollisions()}');if(!R('e.x>800&&e.h==0&&e.hit>0'))throw Error('three-hit anti-pin shift '+R('JSON.stringify([e.x,e.h,e.hit,e.hp,e.q,e.g])'));
R('mode=1;D=.7;wave=9;hitstop=0;kick=sling=0;kickHit=[];spawnWave();E[0].in=0;B.length=0;B.push({x:E[0].x,y:E[0].y,vx:0,vy:0,_I:1,r:7,l:2});upd(1/60)');if(!R('req31()==1&&E[0].p==1&&!E[0].g'))throw Error('Colonel return gate');
R('mode=1;D=.7;wave=13;hitstop=0;kick=sling=0;kickHit=[];spawnWave();E[0].in=0');if(!R("SN[12]=='COBTOPUS PRIME'&&final31==1&&E.length==1&&E[0].b==4&&E[0].g"))throw Error('Prime phase');R('hitstop=0;E[0]._3=1;E[0]._u=.001;B.length=0;upd(.01)');if(!R('E[0]._3==2&&!E[0].g&&bp==2&&B.length==6'))throw Error('Prime open window '+R('JSON.stringify([E[0]._3,E[0].g,bp,B.length,E[0]._u,D,hitstop])'));R('killE(E[0])');if(!R('final31==2&&need31==1&&E.filter(e=>e.b==3).length==2&&E.every(e=>e.g)'))throw Error('split phase');R('hitstop=0;B.push({x:E[0].x,y:E[0].y,vx:0,vy:0,_I:1,r:7,l:2});upd(1/60)');if(!R('!E[0].g&&E[1].g'))throw Error('independent core gate');R('killE(E[0])');if(!R('mode==1&&E.filter(e=>e.b==3).length==1'))throw Error('first core ended fight');R('hitstop=0;B.push({x:E[0].x,y:E[0].y,vx:0,vy:0,_I:1,r:7,l:2});upd(1/60);killE(E[0])');if(R('mode')!==5)throw Error('final core ending');
R('mode=1;D=2.4;wave=13;hitstop=0;kick=sling=0;kickHit=[];spawnWave();killE(E[0])');if(R('need31')!==4)throw Error('Impossible return count');ell.length=0;R("oval(0,0,7,3.5,'#e9b83e')");if(!ell.length||ell.at(-1)[0]!==ell.at(-1)[1])throw Error('returnable kernel not round');
for(let w=1;w<=13;w++){R(`mode=1;D=1;wave=${w};hitstop=0;kick=sling=0;kickHit=[];spawnWave()`);if(R('!!hitW(A.x,A.y,24)||!!hitW(P.x,P.y,21)'))throw Error('unsafe '+w)}
console.log('PASS: v0.32 firing-window Husk, 2-4x distance-scaled returns, closed shields, three-hit anti-pin shifts, Colonel/Prime counterplay, split-core finale, safe stages');
