import {readFileSync} from'node:fs';import vm from'node:vm';
const h=readFileSync('dist/index.html','utf8'),m=h.match(/<script>([\s\S]*?)<\/script>/);if(!m)throw Error('script missing');if(/\bX\.[_$]/.test(m[1]))throw Error('unsafe Canvas API rename');
let tones=0,wakes=0;const p=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});function AC(){this.currentTime=0;this.destination={};this.resume=()=>wakes++;this.createOscillator=()=>({frequency:p(),connect(){},start(){tones++},stop(){}});this.createGain=()=>({gain:p(),connect(){}})}
const x=new Proxy({},{get:(o,k)=>o[k]||(o[k]=()=>{}),set:(o,k,v)=>(o[k]=v,true)}),c={getContext:()=>x,width:960,height:640},s={console,Math,Date,setTimeout:()=>{},clearTimeout:()=>{},requestAnimationFrame:()=>{},document:{querySelector:()=>c},localStorage:{SV:'0,0'},AudioContext:AC,window:null};s.window=s;s.globalThis=s;vm.createContext(s);vm.runInContext(m[1],s);const R=q=>vm.runInContext(q,s),key=k=>s.onkeydown({key:k,repeat:false,preventDefault(){}});
R(`Object.defineProperties(globalThis,{charge:{get(){return _0},set(v){_0=v}},ready:{get(){return _1},set(v){_1=v}},fire:{get(){return _T},set(v){_T=v}},sling:{get(){return _4},set(v){_4=v}},score:{get(){return _5},set(v){_5=v}},wave:{get(){return L},set(v){L=v}},hearts:{get(){return J},set(v){J=v}},kick:{get(){return Z},set(v){Z=v}},kickA:{get(){return $N},set(v){$N=v}},inv:{get(){return Y},set(v){Y=v}},aim:{get(){return O},set(v){O=v}},puT:{get(){return $Q},set(v){$Q=v}},queen:{get(){return _c},set(v){_c=v}},bp:{get(){return F},set(v){F=v}},bt:{get(){return I},set(v){I=v}}});globalThis.reset=$A;globalThis.upd=$B;globalThis.startKick=$C;globalThis.hurt=$D;globalThis.music=$E;globalThis.snd=S;globalThis.spawnWave=$H;globalThis.hitW=$I;globalThis.killE=$c;globalThis.finale=$0`);
if(R('V[0]')!==0||R('typeof V[0]')!='number')throw Error('mute restore');let t0=tones;R('snd(440)');if(tones!=t0)throw Error('muted synthesis');R('V[0]=V[1]=4');
for(const [k,d,n] of [['1',.7,3],['2',1,5],['3',1.6,8],['4',2.4,12]]){R('mode=0');key(k);s.onkeyup({key:k});if(Math.abs(R('D')-d)>1e-9||R('mode')!==1||R('E.length')!==n)throw Error('difficulty '+k)}
R('mode=0;D=2.4');key(' ');if(R('D')!==1||R('E.length')!==5||!wakes)throw Error('Normal shortcut');R('mode=3;D=2.4');key(' ');if(R('D')!==2.4||R('E.length')!==12)throw Error('retry difficulty');
R('mode=1;D=1.6;wave=1;spawnWave()');if(R('E[0].hp')!==1)throw Error('Hard HP changed');R('D=2.4;wave=1;spawnWave()');if(R('E[0].hp')!==1.5)throw Error('Impossible HP');
R('D=1.6;wave=1;spawnWave();puT=5;upd(1)');let ph=R('puT');R('D=2.4;wave=1;spawnWave();puT=5;upd(1)');let pi=R('puT');if(!(pi>ph))throw Error('pickup scarcity');
R('D=1.6;wave=1;spawnWave();E.length=1;Object.assign(E[0],{x:300,y:300,vx:100,vy:0});A.x=700;A.y=300');let q=R('E[0].x');R('upd(.01)');let dh=R('E[0].x')-q;R('D=2.4;wave=1;spawnWave();E.length=1;Object.assign(E[0],{x:300,y:300,vx:100,vy:0});A.x=700;A.y=300');q=R('E[0].x');R('upd(.01)');let di=R('E[0].x')-q;if(!(di>dh*1.1))throw Error('hostile movement');
R('mode=1;D=1.6;wave=1;E.length=0;B=[{x:100,y:200,vx:100,vy:0,team:2,r:5,l:10}];A.x=700;A.y=500');q=R('B[0].x');R('upd(.1)');dh=R('B[0].x')-q;R('D=2.4;wave=1;E.length=0;B=[{x:100,y:200,vx:100,vy:0,team:2,r:5,l:10}];A.x=700;A.y=500');q=R('B[0].x');R('upd(.1)');di=R('B[0].x')-q;if(!(di>dh*1.2))throw Error('projectile speed');
R('D=1.6;wave=9;spawnWave();bp=0;bt=0;upd(.4)');ph=R('bt');R('D=2.4;wave=9;spawnWave();bp=0;bt=0;upd(.4)');pi=R('bt');if(!(pi>ph*1.2))throw Error('Husk cadence');
R('mode=1;D=2.4;wave=13;spawnWave();inv=1e9;killE(E.find(e=>e.type==3))');if(R('mode')!==1||R('queen')!==3||R('E.filter(e=>e.type==3).length')!==2||R('E.filter(e=>e.type==6).length')!==1||R('E.filter(e=>e.type==3&&e.a).length')!==1)throw Error('boss rush launch');
R('killE(E.find(e=>e.type==3))');if(R('mode')!==1)throw Error('boss rush ended early 1');R('killE(E.find(e=>e.type==6))');if(R('mode')!==1)throw Error('boss rush ended early 2');R('killE(E.find(e=>e.type==3))');if(R('mode')!==5||R('queen')!==3)throw Error('Impossible true ending');
R('mode=1;D=1.6;wave=13;spawnWave();killE(E.find(e=>e.type==3))');if(R('mode')!==5||R('queen')===3)throw Error('Hard got boss rush');
R('mode=1;D=1;charge=1;ready=.5;kick=fire=0');s.onkeydown({key:' ',repeat:true,preventDefault(){}});if(R('fire'))throw Error('repeat attack');key(' ');if(R('fire')!==1)throw Error('attack latch');R('upd(1/60)');if(R('fire')||R('kick')<=0)throw Error('attack consume');R('mode=1;K.w=1;fire=1');s.onblur();if(R('mode')!==2||R('fire')||R('Object.keys(K).length'))throw Error('blur pause');
R('mode=1;D=1;wave=9;spawnWave();kick=sling=inv=0');if(R('bp')!==1||R('R.filter(o=>o.d).length')!==2)throw Error('Husk warning');R('(()=>{let o=R.find(o=>o.d);A.x=o.x+o.w/2;A.y=o.y+o.h/2;hearts=13;bt=1.99})()');R('upd(1/60)');if(R('bp')!==2||R('hearts')!==12)throw Error('Husk harden');
for(let w=1;w<=13;w++){R(`D=1;wave=${w};spawnWave()`);if(R('!!hitW(A.x,A.y,24)||!!hitW(P.x,P.y,21)'))throw Error('unsafe '+w)}
R('mode=1;D=2.4;wave=13;spawnWave();inv=1e9;killE(E.find(e=>e.type==3));V[0]=V[1]=0');let mb=0,me=0;for(let i=0;i<600;i++){R('upd(1/60)');mb=Math.max(mb,R('B.length'));me=Math.max(me,R('E.length'));if(!R('Number.isFinite(P.x+P.y+A.x+A.y)'))throw Error('nonfinite Impossible')}if(mb>800||me>40)throw Error('Impossible runaway '+mb+'/'+me);
console.log('PASS: Hard remap, Impossible all-axis scaling + boss rush, input/Husk/safe-stage invariants, bounded encore');
